name: Vercel Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_run:
    workflows: ["Test"]
    types: [completed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Cypress test status
        run: |
          if [ "${{ needs.Cypress_Test.outputs.CYPRESS_STATUS }}" -eq 0 ]; then
            echo "Cypress tests passed, proceeding with build."
            exit 0
          else
            echo "Cypress tests failed, skipping build."
            exit 1
          fi
      - name: Build
        run: npm run build
  Deploy-Production:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
